#pull official base image
FROM python:3.12-slim

#Set working directory and coppy content in container
WORKDIR /backend

#Upgrade packages
RUN apt update && apt install -y \
    libpq-dev python3-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

#Install requirements
RUN pip install --no-cache-dir -r requirements.txt

COPY . /backend

EXPOSE 8000

#Start FastAPI Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]